name: CI/CD Pipeline - Shine Retail App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --if-present

    - name: Lint Helm chart
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm lint ./Retail-chart
        echo "Helm lint passed!"

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/argocd

    - name: Sync ArgoCD
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure
        argocd app sync userprofile-blue-green --force
        echo "Pipeline SUCCESS!"
